version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: parcial_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12345}
      POSTGRES_DB: ${DB_NAME:-parcial_db}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_net
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-parcial_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parcial_api
    restart: unless-stopped
    environment:
      PORT: ${API_PORT:-3000}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-12345}
      DB_NAME: ${DB_NAME:-parcial_db}
      NODE_ENV: production
    ports:
      - "${API_PORT:-3000}:3000"
    networks:
      - app_net
    depends_on:
      db:
        condition: service_healthy

networks:
  app_net:
    driver: bridge
    name: app_net

volumes:
  db_data:
    name: db_data


